set(COMPONENT_SRCS
        ubirch/ubirch_protocol_kex.c
        ubirch/ubirch_protocol.c
        ubirch/digest/sha512.c
        )
set(COMPONENT_ADD_INCLUDEDIRS
        ubirch
        ubirch/digest
        )
set(COMPONENT_REQUIRES
        msgpack-c
        ubirch-mbed-nacl-cm0
        )
register_component()